### ISSUE TITLE
Oauth Headers Error

### ISSUE THREAD

**Issue by frankmaina** [springboardretail/nuorder#2]
Hi, I Keep getting this error, whenever i try to make a get request to a wholesale api.

```
/lib/ruby/gems/2.3.0/gems/nuorder-1.0.0/lib/nuorder/client/oauth.rb:9:in `oauth_headers': uninitialized constant Nuorder::Client::Oauth::SecureRandom (NameError)
Did you mean?  SecurityError
```

**Comment by jstotz** [comment]
Sorry for the delayed reply. This should have been resolved in v1.0.1 (f2dddef9499d1e46d7a4f9f126664c50781e76e1)
